import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.PrintStream;

/**
 * This program searches for the INDY gene on various fruit flies. It was
 * created for CSC 143.
 * 
 * FileNameFilter code is not original and was generated by user: MadConan on
 * StackOverflow This forum accessed 10 Dec 2016:
 * http://stackoverflow.com/questions/30486404/java-list-files-in-a-folder-avoiding-ds-store
 * 
 * @author rachellowy
 * @version 7 Dec 2016
 *
 */

public class GeneLocatorDriver {

	public static void main(String[] args) throws FileNotFoundException {

		DNA INDY = new DNA(new File("../indySequence.txt"), true);

		System.out.println("INDY: " + INDY);

		Genome melagonster = new Genome("melagonster");

		// directory of melagonster DNA
		File melaFiles = new File("../Genomes/melagonster/melagonsterDNA");
		File[] melaDNA = melaFiles.listFiles(new FilenameFilter() {
			@Override
			public boolean accept(File dir, String name) {
				return !name.equals(".DS_Store");
			}
		});
		int location = searchGenome(melaDNA, melagonster, INDY);

		// printFinding
		if (location < 0) {
			System.out.println("\n\nINDY was not found in Drosophila melangontser");
		} else {
			System.out.println("\n\nINDY was found in Drosophila melangontser. \nLocation:  " + melaDNA[location]);
		}

	}

	public static int searchGenome(File[] speciesDNA, Genome genome, DNA gene) throws FileNotFoundException {

		boolean geneLocated = false;
		int index = 0;

		// continues search through DNA until the gene of interest is located,
		// or until there is no more DNA
		while (!geneLocated && index < speciesDNA.length) {

			// adds most recent DNA to Genome
			genome.add(new DNA(speciesDNA[index], false));

			// checks the most recently added DNA for gene of interest
			geneLocated = genome.get(genome.getSize() - 1).contains(gene);

			// does not advance index if gene is found so user gets correct filename
			if (!geneLocated) {
				index += 1;
			}
		}

		if (!geneLocated) {
			index = -1;
		}

		return index;
	}

}
